// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/ant-ling.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "Ling-2.6-1T"
		| "Ling-2.6-flash"
		| "Ring-2.6-1T"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const ANT_LING_MODELS: ModelCatalog<CatalogGroups, "ant-ling"> =
	flattenModelCatalog("ant-ling", typedValues);
