// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cerebras.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "gemma-4-31b"
		| "gpt-oss-120b"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const CEREBRAS_MODELS: ModelCatalog<CatalogGroups, "cerebras"> =
	flattenModelCatalog("cerebras", typedValues);
