// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const CEREBRAS_MODELS = {
	"gpt-oss-120b": {
		id: "gpt-oss-120b",
		name: "GPT OSS 120B",
		api: "openai-completions",
		provider: "cerebras",
		baseUrl: "https://api.cerebras.ai/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.25,
			output: 0.69,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 32768,
	} satisfies Model<"openai-completions">,
	"llama3.1-8b": {
		id: "llama3.1-8b",
		name: "Llama 3.1 8B",
		api: "openai-completions",
		provider: "cerebras",
		baseUrl: "https://api.cerebras.ai/v1",
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.1,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 32000,
		maxTokens: 8000,
	} satisfies Model<"openai-completions">,
	"zai-glm-4.7": {
		id: "zai-glm-4.7",
		name: "Z.AI GLM-4.7",
		api: "openai-completions",
		provider: "cerebras",
		baseUrl: "https://api.cerebras.ai/v1",
		reasoning: false,
		input: ["text"],
		cost: {
			input: 2.25,
			output: 2.75,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 40000,
	} satisfies Model<"openai-completions">,
} as const;
