// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepseek.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "deepseek-v4-flash"
		| "deepseek-v4-flash-vision-exp"
		| "deepseek-v4-pro"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const DEEPSEEK_MODELS: ModelCatalog<CatalogGroups, "deepseek"> =
	flattenModelCatalog("deepseek", typedValues);
