// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"anthropic-messages": Record<
		| "MiniMax-M2.7"
		| "MiniMax-M2.7-highspeed"
		| "MiniMax-M3"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const MINIMAX_CN_MODELS: ModelCatalog<CatalogGroups, "minimax-cn"> =
	flattenModelCatalog("minimax-cn", typedValues);
