// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai-codex.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-codex-responses": Record<
		| "gpt-5.3-codex-spark"
		| "gpt-5.4"
		| "gpt-5.4-mini"
		| "gpt-5.5"
		| "gpt-5.6-luna"
		| "gpt-5.6-sol"
		| "gpt-5.6-terra"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const OPENAI_CODEX_MODELS: ModelCatalog<CatalogGroups, "openai-codex"> =
	flattenModelCatalog("openai-codex", typedValues);
