// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-token-plan-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "MiniMax-M2.5"
		| "deepseek-v3.2"
		| "deepseek-v4-flash"
		| "deepseek-v4-flash-0731"
		| "deepseek-v4-pro"
		| "deepseek-v4-pro-0813"
		| "glm-5"
		| "glm-5.1"
		| "glm-5.2"
		| "kimi-k2.5"
		| "kimi-k2.6"
		| "kimi-k2.7-code"
		| "qwen3.6-flash"
		| "qwen3.6-plus"
		| "qwen3.7-max"
		| "qwen3.7-plus"
		| "qwen3.8-flash"
		| "qwen3.8-max"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const QWEN_TOKEN_PLAN_CN_MODELS: ModelCatalog<CatalogGroups, "qwen-token-plan-cn"> =
	flattenModelCatalog("qwen-token-plan-cn", typedValues);
