// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/together.json" with { type: "json" };
import type { Model } from "../types.ts";

export const TOGETHER_MODELS = values as {
	"MiniMaxAI/MiniMax-M2.7": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M2.7";
		provider: "together";
	};
	"MiniMaxAI/MiniMax-M3": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M3";
		provider: "together";
	};
	"Qwen/Qwen2.5-7B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "Qwen/Qwen2.5-7B-Instruct-Turbo";
		provider: "together";
	};
	"Qwen/Qwen3-235B-A22B-Instruct-2507-tput": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput";
		provider: "together";
	};
	"Qwen/Qwen3.5-397B-A17B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-397B-A17B";
		provider: "together";
	};
	"Qwen/Qwen3.5-9B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-9B";
		provider: "together";
	};
	"Qwen/Qwen3.6-Plus": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.6-Plus";
		provider: "together";
	};
	"Qwen/Qwen3.7-Max": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.7-Max";
		provider: "together";
	};
	"deepseek-ai/DeepSeek-V4-Pro": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Pro";
		provider: "together";
	};
	"essentialai/Rnj-1-Instruct": Model<"openai-completions"> & {
		id: "essentialai/Rnj-1-Instruct";
		provider: "together";
	};
	"google/gemma-4-31B-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31B-it";
		provider: "together";
	};
	"meta-llama/Llama-3.3-70B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.3-70B-Instruct-Turbo";
		provider: "together";
	};
	"moonshotai/Kimi-K2.6": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.6";
		provider: "together";
	};
	"moonshotai/Kimi-K2.7-Code": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.7-Code";
		provider: "together";
	};
	"nvidia/nemotron-3-ultra-550b-a55b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-ultra-550b-a55b";
		provider: "together";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "together";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "together";
	};
	"zai-org/GLM-5": Model<"openai-completions"> & {
		id: "zai-org/GLM-5";
		provider: "together";
	};
	"zai-org/GLM-5.1": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.1";
		provider: "together";
	};
	"zai-org/GLM-5.2": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.2";
		provider: "together";
	};
};
