// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi-token-plan-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "mimo-v2.5"
		| "mimo-v2.5-pro"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const XIAOMI_TOKEN_PLAN_CN_MODELS: ModelCatalog<CatalogGroups, "xiaomi-token-plan-cn"> =
	flattenModelCatalog("xiaomi-token-plan-cn", typedValues);
