// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CatalogGroups = {
	"openai-completions": Record<
		| "mimo-v2.5"
		| "mimo-v2.5-pro"
		| "mimo-v2.5-pro-ultraspeed"
		, object
	>;
};

const typedValues = values as CatalogGroups;

export const XIAOMI_MODELS: ModelCatalog<CatalogGroups, "xiaomi"> =
	flattenModelCatalog("xiaomi", typedValues);
